// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EmblemaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void emblema() {
    driver.get("https://battlelog.battlefield.com/bf4/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".name > a")).click();
    driver.findElement(By.linkText("Customize Emblem")).click();
    driver.findElement(By.linkText("Close")).click();
    driver.findElement(By.cssSelector(".emblem-item:nth-child(4) > a")).click();
    driver.findElement(By.linkText("Close")).click();
    js.executeScript("window.scrollTo(0,186)");
    driver.findElement(By.cssSelector(".upper-canvas")).click();
    driver.findElement(By.cssSelector(".upper-canvas")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".upper-canvas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".upper-canvas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".upper-canvas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".upper-canvas")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".upper-canvas"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("base-page"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("base-page")).click();
    driver.findElement(By.cssSelector(".upper-canvas")).click();
    driver.findElement(By.cssSelector(".color:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".color:nth-child(75)")).click();
    driver.findElement(By.cssSelector("#emblem-action-save > span")).click();
    driver.findElement(By.cssSelector(".emblem-item:nth-child(1) .emblem-image")).click();
    {
      WebElement element = driver.findElement(By.linkText("Close"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Close"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Close"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("Close")).click();
    driver.findElement(By.id("emblem-action-save")).click();
    {
      WebElement element = driver.findElement(By.id("emblem-action-save"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".emblem-item:nth-child(2) > a")).click();
    driver.findElement(By.linkText("Close")).click();
  }
}
