// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificaes() {
    driver.get("https://battlelog.battlefield.com/bf4/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector(".m25"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".active a:nth-child(4) > span")).click();
    {
      WebElement element = driver.findElement(By.linkText("Battlefield 2042"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".RPK74_lineart")).click();
    driver.findElement(By.cssSelector(".active > .loadout-item-info .cog")).click();
    driver.findElement(By.cssSelector("#slot-1 span")).click();
    driver.findElement(By.cssSelector(".row-tight:nth-child(3) > .loadout-item-grid:nth-child(1) li:nth-child(4) > .item-stats-right-col-2")).click();
    driver.findElement(By.id("save-loadout")).click();
    driver.findElement(By.cssSelector(".type-appearance span")).click();
    driver.findElement(By.cssSelector(".locked .items-select-item-image")).click();
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".XP4Custom01"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".XP4Custom01"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    driver.findElement(By.cssSelector(".XP4Custom01")).click();
    driver.findElement(By.cssSelector(".dependency-icon")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".active > .award_mission")).click();
    driver.findElement(By.cssSelector(".active > .award_mission")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".active > .award_mission"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".active > .award_mission")).click();
    driver.findElement(By.cssSelector(".active > .award_mission")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".active > .award_mission"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".track-assignment")).click();
    driver.findElement(By.cssSelector(".btn-container > .btn-primary")).click();
    driver.findElement(By.cssSelector(".unlocks > a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".has-dropdown:nth-child(2) > .wfont"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".active a:nth-child(4) > span")).click();
    driver.findElement(By.cssSelector(".RPK74_lineart")).click();
    driver.findElement(By.cssSelector("#slot-1 span")).click();
    driver.findElement(By.cssSelector("#slot-5 span")).click();
    driver.findElement(By.cssSelector(".C100_lineart")).click();
    driver.findElement(By.id("save-loadout")).click();
  }
}
